name: Build Opera Proxy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
      ver: ${{ steps.get_ver.outputs.ver }}
    steps:
      - name: Get Latest Version
        id: get_ver
        run: |
          VER=$(curl -s https://api.github.com/repos/hirajanwin/opera-proxy/tags | grep '"name":' | head -n 1 | sed -E 's/.*"v([^"]+)".*/\1/' || echo "1.0.0")
          [ -z "$VER" ] && VER="1.0.0"
          echo "ver=$VER" >> $GITHUB_OUTPUT
          echo "VER=$VER" >> $GITHUB_ENV

      - name: Check Release
        id: check
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ env.VER }})
          echo "exists=$([ "$HTTP_STATUS" -eq 200 ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

  build:
    needs: check-version
    if: needs.check-version.outputs.exists == 'false'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "mipsle"
            pkg_arch: "mipsel_24kc"
            goarch: "mipsle"
            gomips: "softfloat"
            sdk_url: "https://downloads.openwrt.org/releases/25.12.0/targets/ramips/mt7621/openwrt-sdk-25.12.0-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
          - arch: "arm64"
            pkg_arch: "aarch64_cortex-a53"
            goarch: "arm64"
            gomips: ""
            sdk_url: "https://downloads.openwrt.org/releases/25.12.0/targets/mediatek/filogic/openwrt-sdk-25.12.0-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Compile Opera Proxy Binary
        run: |
          git clone https://github.com/hirajanwin/opera-proxy.git source
          cd source
          GOOS=linux GOARCH=${{ matrix.goarch }} GOMIPS=${{ matrix.gomips }} go build -ldflags="-s -w" -o ../opera-proxy-bin
          cd ..

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libncurses5-dev zstd

      - name: Setup SDK
        run: |
          wget -O sdk.tar.zst ${{ matrix.sdk_url }}
          mkdir sdk
          tar --use-compress-program=unzstd -xf sdk.tar.zst -C sdk --strip-components=1

      - name: Prepare Package
        run: |
          mkdir -p opera-proxy/files/usr/bin
          cp opera-proxy-bin opera-proxy/files/usr/bin/opera-proxy
          chmod +x opera-proxy/files/usr/bin/opera-proxy
          
          VER="${{ needs.check-version.outputs.ver }}"
          [ -z "$VER" ] || [ "$VER" = "null" ] && VER="1.0.0"
          sed -i "s/^PKG_VERSION:=.*$/PKG_VERSION:=$VER/" opera-proxy/Makefile
          cp -r opera-proxy sdk/package/

      - name: Compile APK
        run: |
          cd sdk
          make oldconfig || make defconfig
          ./scripts/feeds update base
          ./scripts/feeds install -a
          echo "CONFIG_PACKAGE_opera-proxy=y" >> .config
          make defconfig
          make package/opera-proxy/compile V=s
          
          echo "=== Поиск и переименование APK ==="
          mkdir -p ../output-artifacts
          # Здесь мы добавляем pkg_arch в имя файла
          find bin/ -name "opera-proxy*.apk" -exec cp {} ../output-artifacts/opera-proxy-${{ matrix.pkg_arch }}.apk \;
          
          if [ -z "$(ls -A ../output-artifacts/)" ]; then
            echo "Файл не найден!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opera-proxy-${{ matrix.pkg_arch }}
          path: output-artifacts/
          if-no-files-found: error

  publish:
    needs: [check-version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check-version.outputs.ver }}
          files: artifacts/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
